fix: update opacity script to make change to alacritty.toml file

diff --git a/bin/opacity b/bin/opacity
--- a/bin/opacity
+++ b/bin/opacity
@@ -3,8 +3,8 @@
 # Change the opacity of alacrity instantly from anywhere without opening the
 # configuration file
 
-yml="$HOME/.config/alacritty/alacritty.yml"
-[ ! -f "$yml" ] && echo "Could not find alacritty config at $yml" && exit 1
+toml="$HOME/.config/alacritty/alacritty.toml"
+[ ! -f "$toml" ] && echo "Could not find alacritty config at $toml" && exit 1
 
 if [ "$#" -ne 1 ]; then
 	echo "Usage: ${0##/} <decimal>"
@@ -18,10 +18,10 @@ if ! expr "$1" : "$decimal" >/dev/null 2>&1; then
 	exit 1
 fi
 
-updated=$(sed "s/opacity: [0-1]\.\{0,1\}\([0-9]\{1,\}\)\{0,1\}/opacity: $1/" "$yml")
-echo "$updated" >"$yml"
+updated=$(sed "s/opacity = [0-1]\.\{0,1\}\([0-9]\{1,\}\)\{0,1\}/opacity = $1/" "$toml")
+echo "$updated" >"$toml"
 
 # can be an alternative way, maybe even better way, but I prefer the above
 # approach
 #
-# perl -p -i -e 's/^background_opacity:\s*\S+/background_opacity: .'$1'/' $yml
+# perl -p -i -e 's/^background_opacity:\s*\S+/background_opacity: .'$1'/' $toml
