update setup script to use new install scripts

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,29 +1,88 @@
 #!/bin/sh
 
-CURR_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)
-# shellcheck disable=2139
-alias ghdl="$CURR_DIR/bin/ghdl"
+# setup environment
+# first check dependencies
+# install brew on mac
+# install curl and git on *unix systems
 
-_depends() { have "$1" ||
-	{ echo "${0##*/} depends on $1, please install and try again." && exit 1; }; }
+depends curl && exit 1
+depends git && exit 1
 
-# Define ASCII color variables
-RED='\033[0;31m'
-GREEN='\033[0;32m'
-# YELLOW='\033[0;33m'
-NC='\033[0m' # No Color
-
-_depends curl
-_depends git
-
-setup_env() {
-	# shellcheck disable=2016
-	echo 'export PATH=.:"$PATH"'
-	# shellcheck disable=2016
-	echo 'export PATH="$PATH":~/.local/bin'
+_bat() {
+	have bat && return
+	if [ "$(uname)" = 'Darwin' ]; then
+		depends brew && return 1
+		brew install bat
+		return
+	elif [ "$(uname)" = 'Linux' ]; then
+		install-bat
+	fi
 }
 
-eval "$(setup_env)"
+_brew() {
+	echo "TODO: install brew"
+}
+
+_curl() {
+	echo "TODO: install curl"
+}
+
+_eza() {
+	have eza && return
+	if [ "$(uname)" = 'Darwin' ]; then
+		depends brew && return 1
+		brew install eza
+		return
+	elif [ "$(uname)" = 'Linux' ]; then
+		install-eza
+	fi
+	ln -sf "$(which eza)" ~/.local/bin/exa
+}
+
+_fd() {
+	have fd && return
+	if [ "$(uname)" = 'Darwin' ]; then
+		depends brew && return 1
+		brew install fd
+		return
+	elif [ "$(uname)" = 'Linux' ]; then
+		install-fd
+	fi
+}
+
+_fzf() {
+	have fzf && return
+	spinner curl -LsS https://raw.githubusercontent.com/junegunn/fzf/master/install -o install
+	spinner bash ./install --all
+	rm ./install
+	have fzf-tmux && return
+	spinner curl -LsS https://raw.githubusercontent.com/junegunn/fzf/master/bin/fzf-tmux -o "$SCRIPTS"/fzf-tmux
+	chmox "$SCRIPTS"/fzf-tmux
+}
+
+_git() {
+	echo "TODO: install git"
+}
+
+_gitmux() {
+	have gitmux && return
+	install-gitmux
+}
+
+_gitui() {
+	have gitui && return
+	install-gitui
+}
+
+_go() {
+	depends wget && return 1
+	mkdir temp && { cd temp || :; }
+	wget https://git.io/go-installer.sh
+	chmox go-installer.sh
+	bash go-installer.sh
+	rm go*
+	cd ..
+}
 
 _starship() {
 	have starship && return
@@ -32,9 +91,34 @@ _starship() {
 		sh starship.sh -y 1>/dev/null 2>&1
 		rm starship.sh
 	else
-		echo "${RED}Couldn't install starship${NC}"
+		error "Couldn't install starship"
 	fi
-	echo "${GREEN}starship successfully installed${NC}"
+	success "starship successfully installed"
+}
+
+_tmux() {
+	case "$DISTRO" in
+	Debian | Ubuntu) sudo apt install tmux -y ;;
+	Fedora | CentOS | RHEL) dnf install tmux -y ;;
+	openSUSE | SUSE) zypper install tmux -y ;;
+	Arch\ Linux) sudo pacman -S --nocomfirm tmux ;;
+	*) return 1 ;;
+	esac
+	depends tmux && return 1
+}
+
+setup_tmux_complete() {
+	_tmux
+	_yq
+	_gitmux
+	_gitui
+	_fd
+	_fzf
+}
+
+_yq() {
+	have yq && return
+	install-yq
 }
 
 _zap_zsh() {
@@ -44,137 +128,55 @@ _zap_zsh() {
 		zsh install.zsh --branch release-v1 --keep
 		rm install.zsh
 	else
-		echo "${RED}Couldn't install zap-zsh${NC}"
+		error "Couldn't install zap-zsh"
 	fi
-	echo "${GREEN}zap-zsh successfully installed${NC}"
+	success "zap-zsh successfully installed"
 }
 
-_eza() {
-	have eza && return
-	ghdl eza-community/eza
-	tar -xf eza-latest*
-	mv eza ~/.local/bin
-	ln -sf ~/.local/bin/eza ~/.local/bin/exa
-	rm eza-latest*
-}
-
-_bat() {
-	have bat && return
-	if [ "$(uname)" = 'Darwin' ]; then
-		_depends brew
-		brew install bat
-		return
-	fi
-	ghdl sharkfp/bat
-	tar -xf bat-latest.tar.gz
-	install_path=~/.local/bin/bat
-	asset=$(find . -name 'bat-*' -type d)
-	mv "$asset"/bat $install_path
-	mv "$asset"/bat.1 /usr/local/share/man/
-	rm -r bat-*
-}
-
-_fd() {
-	have eza && return
-	if [ "$(uname)" = 'Darwin' ]; then
-		_depends brew
-		brew install fd
-		return
-	fi
-	ghdl sharkfp/fd
-	tar -xf fd-latest.tar.gz
-	install_path=~/.local/bin/fd
-	asset=$(find . -name 'fd-*' -type d)
-	mv "$asset"/fd $install_path
-	mv "$asset"/fd.1 /usr/local/share/man/
-	rm -r fd-*
-}
-
-setup_zsh() {
-	_depends zsh
+_zsh() {
+	depends zsh && return 1
+	case "$DISTRO" in
+	Debian | Ubuntu) sudo apt install zsh -y ;;
+	Fedora | CentOS | RHEL) dnf install zsh -y ;;
+	openSUSE | SUSE) zypper install zsh -y ;;
+	Arch\ Linux) sudo pacman -S --nocomfirm zsh ;;
+	*) return 1 ;;
+	esac
 	echo export ZDOTDIR="$HOME"/.config/zsh >>"$HOME"/.profile
-	_starship
-	_zap_zsh
-	echo "${GREEN}base zsh shell setup complete${NC}"
+	success "Successfully installed zsh"
 }
 
 setup_zsh_complete() {
-	setup_zsh
+	_zsh
+	_starship
+	_zap_zsh
 	_eza
 	_bat
-}
-
-_gitmux() {
-	have gitmux && return
-	ghdl arl/gitmux
-	tar -xf gitmux-latest
-	rm gitmux-latest*
-	mv gitmux "$HOME"/.local/bin/gitmux
-	rm LICENSE README.md
-	echo "${GREEN}gitmux successfully installed${NC}"
-}
-
-_yq() {
-	have yq && return
-	ghdl mikefarah/yq
-	install_path="$HOME"/.local/bin/yq
-	asset=yq-latest
-	mv "$asset" "$install_path"
-	chmod +x "$install_path"
-	echo "${GREEN}yq successfully installed${NC}"
-}
-
-_gitui() {
-	have gitui && return
-	mkdir temp && { cd temp || true; }
-	ghdl extrawurst/gitui
-	tar -xf gitui-latest*
-	mv gitui ~/.local/bin
-	rm gitui-latest*
-	cd .. && rm -r temp
-}
-
-_fzf() {
-	spinner curl -LsS https://raw.githubusercontent.com/junegunn/fzf/master/install -o install
-	spinner bash ./install --no-key-bindings --completion --no-update-rc
-	rm ./install
-}
-
-setup_tmux() {
-	_depends tmux
-}
-
-setup_tmux_complete() {
-	setup_tmux
-	_yq
-	_gitmux
-	_gitui
-	_fd
-	_fzf
-}
-
-install_go() {
-	_depends wget
-	mkdir temp && { cd temp || :; }
-	wget https://git.io/go-installer.sh
-	chmod +x go-installer.sh
-	bash go-installer.sh
-	rm go*
-	cd ..
+	success "base zsh shell setup complete"
 }
 
 setup_neovim() {
-	bin/install-neovim.sh
+	install-neovim.sh
 }
 
+DISTRO=$(distro | cut -d ':' -f1)
+
+# shellcheck disable=2016
+setup_env() {
+	echo 'export PATH=.:"$PATH"'
+	echo 'export PATH="$PATH":~/.local/bin'
+}
+
+eval "$(setup_env)"
+
 case "$1" in
-zsh) setup_zsh ;;
-tmux) setup_tmux ;;
+zsh) _zsh ;;
+tmux) _tmux ;;
 nvim) setup_neovim ;;
 env) setup_env ;;
 fzf) _fzf ;;
 bat) _bat ;;
-go) install_go ;;
+go) _go ;;
 all | '')
 	setup_zsh_complete
 	setup_tmux_complete
